// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK3Fb2VnKcSG5xb5NTAg8X0hZiJqncDas',
    appId: '1:765699185571:web:a0958e7f186ec9a3265816',
    messagingSenderId: '765699185571',
    projectId: 'my-test-callapp',
    authDomain: 'my-test-callapp.firebaseapp.com',
    storageBucket: 'my-test-callapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5RAmte6bXdPSBm3u6P2uM5LX0HPjvVpk',
    appId: '1:765699185571:android:52024561bfdc8269265816',
    messagingSenderId: '765699185571',
    projectId: 'my-test-callapp',
    storageBucket: 'my-test-callapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb7oqoRvW6rMbSZ-0XsJT0NXLOY5pFXUE',
    appId: '1:765699185571:ios:35c56d11f1bcac6e265816',
    messagingSenderId: '765699185571',
    projectId: 'my-test-callapp',
    storageBucket: 'my-test-callapp.firebasestorage.app',
    iosBundleId: 'com.example.callApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb7oqoRvW6rMbSZ-0XsJT0NXLOY5pFXUE',
    appId: '1:765699185571:ios:35c56d11f1bcac6e265816',
    messagingSenderId: '765699185571',
    projectId: 'my-test-callapp',
    storageBucket: 'my-test-callapp.firebasestorage.app',
    iosBundleId: 'com.example.callApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK3Fb2VnKcSG5xb5NTAg8X0hZiJqncDas',
    appId: '1:765699185571:web:73b8c2a1f15deb28265816',
    messagingSenderId: '765699185571',
    projectId: 'my-test-callapp',
    authDomain: 'my-test-callapp.firebaseapp.com',
    storageBucket: 'my-test-callapp.firebasestorage.app',
  );
}
